const customerData = [
  {
    Org_Id: '66158fe71bfe10b58cb23eea',
    Customer_ID: 123123,
    Customer: 'Hilton',
    Contact_Name: 'Chris Evans',
    Email: 'chris.evans@hiltonbook.com',
    ARR: 321373,
    Licenses_Purchased: 68,
    Licenses_Used: 48,
    Renewal_Date: '2025-08-25',
    CSM_Agent: 'bhattachas@hotmail.com',
    Account_Executive: 'account1@company.com',
    Health_Score: 4,
    Login_Count: 226,
    Main_Feature_Usage_Count: 61,
    Total_Ticket_Count: 59,
    Open_Ticket_Count: 5,
    Escalated_Ticket_Count: 4,
    Closed_Ticket_Count: 66,
  },
  {
    Org_Id: '66158fe71bfe10b58cb23eea',
    Customer_ID: 123123,
    Customer: 'HolidayInn',
    Contact_Name: 'Sophia Clark',
    Email: 'sophia.clark@holidayinnbook.com',
    ARR: 216217,
    Licenses_Purchased: 35,
    Licenses_Used: 35,
    Renewal_Date: '2025-03-13',
    CSM_Agent: 'bhattachas@hotmail.com',
    Account_Executive: 'account2@company.com',
    Health_Score: 6,
    Login_Count: 279,
    Main_Feature_Usage_Count: 292,
    Total_Ticket_Count: 23,
    Open_Ticket_Count: 5,
    Escalated_Ticket_Count: 2,
    Closed_Ticket_Count: 20,
  },
  {
    Org_Id: '66158fe71bfe10b58cb23eea',
    Customer_ID: 123123,
    Customer: 'Marriott',
    Contact_Name: 'Emma Davis',
    Email: 'emma.davis@marriott.com',
    ARR: 161633,
    Licenses_Purchased: 68,
    Licenses_Used: 43,
    Renewal_Date: '2025-03-01',
    CSM_Agent: 'bhattachas@hotmail.com',
    Account_Executive: 'account3@company.com',
    Health_Score: 8,
    Login_Count: 183,
    Main_Feature_Usage_Count: 25,
    Total_Ticket_Count: 45,
    Open_Ticket_Count: 9,
    Escalated_Ticket_Count: 5,
    Closed_Ticket_Count: 80,
  },
  {
    Org_Id: '66158fe71bfe10b58cb23eea',
    Customer_ID: 123123,
    Customer: 'Hyatt',
    Contact_Name: 'John Doe',
    Email: 'john.doe@hyatt.com',
    ARR: 419571,
    Licenses_Purchased: 22,
    Licenses_Used: 18,
    Renewal_Date: '2024-11-15',
    CSM_Agent: 'bhattachas@hotmail.com',
    Account_Executive: 'account4@company.com',
    Health_Score: 5,
    Login_Count: 121,
    Main_Feature_Usage_Count: 198,
    Total_Ticket_Count: 87,
    Open_Ticket_Count: 4,
    Escalated_Ticket_Count: 2,
    Closed_Ticket_Count: 65,
  },
  {
    Org_Id: '66158fe71bfe10b58cb23eea',
    Customer_ID: 123123,
    Customer: 'Sheraton',
    Contact_Name: 'Jane Smith',
    Email: 'jane.smith@sheraton.com',
    ARR: 108719,
    Licenses_Purchased: 40,
    Licenses_Used: 17,
    Renewal_Date: '2025-03-26',
    CSM_Agent: 'bhattachas@hotmail.com',
    Account_Executive: 'account5@company.com',
    Health_Score: 9,
    Login_Count: 82,
    Main_Feature_Usage_Count: 224,
    Total_Ticket_Count: 95,
    Open_Ticket_Count: 6,
    Escalated_Ticket_Count: 0,
    Closed_Ticket_Count: 62,
  },
  {
    Org_Id: '66158fe71bfe10b58cb23eea',
    Customer_ID: 123123,
    Customer: 'Ritz-Carlton',
    Contact_Name: 'Robert Lee',
    Email: 'robert.lee@ritz.com',
    ARR: 462187,
    Licenses_Purchased: 25,
    Licenses_Used: 4,
    Renewal_Date: '2025-02-04',
    CSM_Agent: 'sarah@test.com',
    Account_Executive: 'account6@company.com',
    Health_Score: 8,
    Login_Count: 212,
    Main_Feature_Usage_Count: 134,
    Total_Ticket_Count: 66,
    Open_Ticket_Count: 6,
    Escalated_Ticket_Count: 5,
    Closed_Ticket_Count: 77,
  },
  {
    Org_Id: '66158fe71bfe10b58cb23eea',
    Customer_ID: 123123,
    Customer: 'Four Seasons',
    Contact_Name: 'Alice Johnson',
    Email: 'alice.johnson@fourseasons.com',
    ARR: 248662,
    Licenses_Purchased: 46,
    Licenses_Used: 21,
    Renewal_Date: '2025-08-28',
    CSM_Agent: 'jim@test.com',
    Account_Executive: 'account7@company.com',
    Health_Score: 6,
    Login_Count: 224,
    Main_Feature_Usage_Count: 60,
    Total_Ticket_Count: 28,
    Open_Ticket_Count: 2,
    Escalated_Ticket_Count: 2,
    Closed_Ticket_Count: 76,
  },
  {
    Org_Id: '66158fe71bfe10b58cb23eea',
    Customer_ID: 123123,
    Customer: 'Intercontinental',
    Contact_Name: 'Mark Brown',
    Email: 'mark.brown@intercontinental.com',
    ARR: 308017,
    Licenses_Purchased: 100,
    Licenses_Used: 89,
    Renewal_Date: '2025-06-27',
    CSM_Agent: 'david@test.com',
    Account_Executive: 'account8@company.com',
    Health_Score: 6,
    Login_Count: 179,
    Main_Feature_Usage_Count: 39,
    Total_Ticket_Count: 33,
    Open_Ticket_Count: 9,
    Escalated_Ticket_Count: 0,
    Closed_Ticket_Count: 11,
  },
  {
    Org_Id: '66158fe71bfe10b58cb23eea',
    Customer_ID: 123123,
    Customer: 'Best Western',
    Contact_Name: 'Sara Wilson',
    Email: 'sara.wilson@bestwestern.com',
    ARR: 427703,
    Licenses_Purchased: 79,
    Licenses_Used: 37,
    Renewal_Date: '2025-06-17',
    CSM_Agent: 'sarah@test.com',
    Account_Executive: 'account9@company.com',
    Health_Score: 2,
    Login_Count: 75,
    Main_Feature_Usage_Count: 208,
    Total_Ticket_Count: 20,
    Open_Ticket_Count: 7,
    Escalated_Ticket_Count: 4,
    Closed_Ticket_Count: 29,
  },
  {
    Org_Id: '66158fe71bfe10b58cb23eea',
    Customer_ID: 123123,
    Customer: 'Radisson',
    Contact_Name: 'David Turner',
    Email: 'david.turner@radisson.com',
    ARR: 370529,
    Licenses_Purchased: 54,
    Licenses_Used: 25,
    Renewal_Date: '2025-08-31',
    CSM_Agent: 'jim@test.com',
    Account_Executive: 'account10@company.com',
    Health_Score: 8,
    Login_Count: 336,
    Main_Feature_Usage_Count: 148,
    Total_Ticket_Count: 83,
    Open_Ticket_Count: 6,
    Escalated_Ticket_Count: 5,
    Closed_Ticket_Count: 99,
  },
];

module.exports = customerData;
