const loginData = [
  {
    hotel: 'Hilton',
    system: 'PMS',
    email: 'bob.lee@hiltonbook.com',
    date: '2024-09-10',
    time: '14:03:38',
    action: 'Login',
  },
  {
    hotel: 'Hilton',
    system: 'PMS',
    email: 'bob.lee@hiltonbook.com',
    date: '2024-09-08',
    time: '14:03:38',
    action: 'Login',
  },
  {
    hotel: 'Hilton',
    system: 'PMS',
    email: 'alice.johnson@hiltonbook.com',
    date: '2024-08-12',
    time: '14:03:38',
    action: 'Login',
  },
  {
    hotel: 'Hilton',
    system: 'PMS',
    email: 'jane.smith@hiltonbook.com',
    date: '2024-08-27',
    time: '14:03:38',
    action: 'Login',
  },
  {
    hotel: 'Hilton',
    system: 'PMS',
    email: 'chris.evans@hiltonbook.com',
    date: '2024-09-18',
    time: '14:03:38',
    action: 'Login',
  },
  {
    hotel: 'Hilton',
    system: 'PMS',
    email: 'john.doe@hiltonbook.com',
    date: '2024-09-04',
    time: '14:03:38',
    action: 'Login',
  },
  {
    hotel: 'Hilton',
    system: 'PMS',
    email: 'alice.johnson@hiltonbook.com',
    date: '2024-09-07',
    time: '14:03:38',
    action: 'Login',
  },
  {
    hotel: 'Hilton',
    system: 'PMS',
    email: 'bob.lee@hiltonbook.com',
    date: '2024-09-04',
    time: '14:03:38',
    action: 'Login',
  },
  {
    hotel: 'Hilton',
    system: 'PMS',
    email: 'bob.lee@hiltonbook.com',
    date: '2024-09-19',
    time: '14:03:38',
    action: 'Login',
  },
  {
    hotel: 'Hilton',
    system: 'PMS',
    email: 'bob.lee@hiltonbook.com',
    date: '2024-09-03',
    time: '14:03:38',
    action: 'Login',
  },
  {
    hotel: 'Hilton',
    system: 'PMS',
    email: 'alice.johnson@hiltonbook.com',
    date: '2024-09-10',
    time: '14:03:38',
    action: 'Login',
  },
  {
    hotel: 'Hilton',
    system: 'PMS',
    email: 'chris.evans@hiltonbook.com',
    date: '2024-08-28',
    time: '14:03:38',
    action: 'Login',
  },
  // Continue for other records...
  {
    hotel: 'HolidayInn',
    system: 'PMS',
    email: 'steve.adams@holidayinnbook.com',
    date: '2024-08-29',
    time: '14:16:55',
    action: 'Login',
  },
  {
    hotel: 'HolidayInn',
    system: 'PMS',
    email: 'emma.davis@holidayinnbook.com',
    date: '2024-08-15',
    time: '14:16:55',
    action: 'Login',
  },
  {
    hotel: 'HolidayInn',
    system: 'PMS',
    email: 'sophia.clark@holidayinnbook.com',
    date: '2024-08-18',
    time: '14:16:55',
    action: 'Login',
  },
  {
    hotel: 'HolidayInn',
    system: 'PMS',
    email: 'anna.brown@holidayinnbook.com',
    date: '2024-08-31',
    time: '14:16:55',
    action: 'Login',
  },
  {
    hotel: 'HolidayInn',
    system: 'PMS',
    email: 'steve.adams@holidayinnbook.com',
    date: '2024-06-30',
    time: '14:16:55',
    action: 'Login',
  },
  // Continue for other HolidayInn records...
];

const featureData = [
  {
    hotel: 'Hilton',
    system: 'PMS',
    email: 'bob.lee@hiltonbook.com',
    date: '2024-09-10',
    time: '14:03:38',
    action: 'Checkin',
  },
  {
    hotel: 'Hilton',
    system: 'PMS',
    email: 'bob.lee@hiltonbook.com',
    date: '2024-09-08',
    time: '14:03:38',
    action: 'Reservation',
  },
  {
    hotel: 'Hilton',
    system: 'PMS',
    email: 'alice.johnson@hiltonbook.com',
    date: '2024-08-12',
    time: '14:03:38',
    action: 'Reservation',
  },
  {
    hotel: 'Hilton',
    system: 'PMS',
    email: 'jane.smith@hiltonbook.com',
    date: '2024-08-27',
    time: '14:03:38',
    action: 'Reservation',
  },
  {
    hotel: 'Hilton',
    system: 'PMS',
    email: 'chris.evans@hiltonbook.com',
    date: '2024-09-18',
    time: '14:03:38',
    action: 'Group Reservation',
  },
  {
    hotel: 'Hilton',
    system: 'PMS',
    email: 'john.doe@hiltonbook.com',
    date: '2024-09-04',
    time: '14:03:38',
    action: 'Group Reservation',
  },
];

module.exports = featureData;
